(() => {
'use strict';
const A=window.ASSETS,C=window.CONTENT,UI=window.PFUI,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!UI)throw new Error('PreFoundation live component runtime is required. Run component-library/sync_runtime.py for this lesson.');
const asset=id=>A.byId[id]||A.files.find(f=>f.name===id)?.url||'';
const image=(id,cls='hero-img',alt='')=>`<img class="${cls}" src="${asset(id)}" alt="${esc(alt)}">`;
const H=['play football','play basketball','play badminton','play tennis','go swimming','go cycling','go camping','go jogging','go hiking','do yoga','do karate','draw pictures','paint pictures','take photos','sing','dance','play an instrument','play computer games','watch TV','watch videos','go on social media','listen to music','make TikTok videos','make YouTube videos'];
const hid=n=>'H'+String(n).padStart(2,'0');const stages=['Welcome','1. Lead-in','2. Vocabulary — Hobbies','3. Practice','Break','4. Reading — The Missing Crown','5. Consolidation'];
const D=[];function add(stage,type,title,props={}){D.push({stage,type,title,...props});}function steps(title,items,img,stage,notes){add(stage,'instructions',title,{items,img,notes});}
const teacherBase='Dạy theo DLP. Next chuyển tới bước tiếp theo; Back quay lại giữ lựa chọn. Dùng thẻ/bảng con vật lý khi học offline. Không chiếu cửa sổ giáo viên lên TV.';
add(0,'cover','Names of hobbies',{img:'MM01',notes:'Bài 120 phút gồm nghỉ 5 phút. Chuẩn bị handout, thẻ hobby, thẻ PLAY/GO/DO/MAKE và bảng con. Mở Teacher view trên màn hình laptop riêng, mở màn hình trình chiếu trên TV ở chế độ Extend (không Mirror). Có thể in teacher-guide.html nếu chỉ dùng một màn hình. Nội dung practice mới được ghi rõ trong ghi chú.'});
steps('Would You Rather?',['Stand in the middle of the classroom.','Look at the pictures and listen.','Step left or right. Choose your favourite!'],'A01',1,'10 phút cả stage. Chỉ đọc hai full hobby phrases mỗi lượt; không yêu cầu HS nói hoàn chỉnh ở bước này. Sau vài lượt hỏi nhanh 1–2 HS. Online: giơ tay trái/phải hoặc poll.');
const pairs=[[1,18],[5,7],[12,14],[2,3],[15,16],[6,9],[11,10],[20,22],[17,24],[8,21]];
add(2,'map','Hobbies — the big picture',{img:'MM01',notes:'Chốt ba nhóm sau khi HS đã tự phân loại. Drill WHOLE PHRASES ở các trang kế tiếp.'});
add(2,'map','Sports — PLAY, GO and DO',{img:'MM02',notes:'Cho học sinh nhìn mental model Sports trước khi đi vào từng cụm từ.'});
add(2,'map','Art — the big picture',{img:'MM03',notes:'Cho học sinh nhìn mental model Art trước khi đi vào từng cụm từ.'});
add(2,'map','Technology & Media — the big picture',{img:'MM04',notes:'Cho học sinh nhìn mental model Technology & Media trước khi đi vào từng cụm từ.'});
[[1,2,3,4],[5,6,7,8,9],[10,11]].forEach((ids,i)=>add(2,'vocab',['SPORTS · PLAY','SPORTS · GO','SPORTS · DO'][i],{ids,notes:'Drill cả cụm, không drill noun riêng. Nhấn badminton, cycling, jogging, hiking, karate khi có.'}));
[[12,13,14],[15,16,17],[18,19,20],[21,22],[23,24]].forEach((ids,i)=>add(2,'vocab',i<2?'ART':'TECHNOLOGY & MEDIA',{ids,notes:'Cho HS nhìn hình, đọc whole phrase. Nhấn mạo từ/giới từ: play AN instrument, go ON social media, listen TO music.'}));
steps('Organise the hobbies',['Work in groups. Look at your hobby cards.','Make three groups: Sports, Art, Technology & Media.','Discuss your choices.'],'A02',2,'25 phút cả stage. Cho HS phân loại thẻ vật lý. Sau đó dùng các ví dụ tương tác để kiểm tra.');
add(2,'sortGame','Which group?',{rounds:[1,14,22].map(n=>({h:n,correct:n<=11?0:n<=17?1:2})),notes:'Mini app 3 lượt. HS phân loại từng hobby; sai rung đỏ và được thử lại, đúng chuyển xanh. Dùng nút Next item trong app, Reset để làm lại.'});
steps('Can we organise sports again?',['Look at your sports cards.','Find the first word in each phrase.','Make three groups: PLAY, GO and DO.'],'Organise Sports - Activity Illustration.png',2,'Elicit cách tổ chức sâu hơn: cùng nhóm Sports, chia theo verb. Cho HS thử rồi Next chữa theo từng nhóm.');
add(2,'organise','Organise it. Remember it.',{notes:'So sánh với danh sách random Stage 1. Chốt: Don’t learn vocabulary randomly. Organise it. Next sang practice.'});
steps('Choose the Right Card',['Work in teams.','Look at the words on screen.','Raise PLAY, GO, DO or MAKE.','Fastest correct team gets 1 point.'],'A03',3,'35 phút cho cả ba practices. Bộ 12 lượt này được biên soạn bổ sung từ word list. HS giơ thẻ; GV có thể click đáp án hoặc Next để chữa.');
add(3,'verbGame','Choose the Right Card',{rounds:C.proposedPractice.rightCard,notes:'Mini app 12 lượt. Cho đội giơ thẻ PLAY/GO/DO/MAKE rồi mới click. Sai rung đỏ và thử lại; đúng chuyển xanh. Next item nằm trong app.'});
steps('Charades',['One player takes a secret card.','Act it out. No speaking!','Your team has 10 seconds to guess.','Say the whole phrase to get a point.'],'A04',3,'Dùng 24 thẻ Charades đã có. Bộ trình chiếu đề xuất 8 lượt mẫu; có thể dùng thêm thẻ in. Chỉ người diễn được xem thẻ. Nếu hết 10 giây chưa đoán được, đội khác giành quyền. Cửa sổ GV có secret phrase; học sinh chỉ thấy timer.');
add(3,'charadeGame','Charades',{rounds:[7,14,17,6,10,23,13,21],notes:'Mini app 8 lượt. Secret phrase chỉ xuất hiện trong Teacher View. Student screen không lộ phrase trước khi giáo viên bấm Reveal.'});
steps('Tiny Word Detective',['Listen carefully. Use your mini whiteboard.','Round 1: write the missing word.','Round 2: fix the wrong word — or cross it out.'],'A05',3,'Giáo viên đọc từ Teacher view hoặc teacher-guide.html. Không chiếu câu đọc. GV đọc lại câu hoàn chỉnh sau mỗi lượt. Hai bộ 6 câu được biên soạn bổ sung, chỉ tập trung tiny words.' );
add(4,'break','Break time',{notes:'Nghỉ 5 phút. Next bắt đầu timer; khi lớp sẵn sàng Next sang phần Reading. Không tự chuyển slide để giáo viên kiểm soát nhịp.'});
add(5,'princessMatch','Who is who?',{notes:'40 phút cả Reading. Kéo từng tên tới đúng nhân vật: trái Rapunzel, giữa Moana, phải Ariel. Sai rung đỏ và thử lại; Reset làm lại toàn bộ.'});
add(5,'predict','What do you think their hobbies are?',{notes:'Cho dự đoán hobbies, GV ghi lại trên bảng để so sánh sau khi đọc. Không chốt đáp án sớm.'});
steps('Before you read',['Read the questions first.','Look at each gap. Predict the word form.','Read the story and find evidence.'],'A06',5,'Cho HS mở handout pages 10–11 trước khi đọc. Lần lượt preview cả 5 MCQ và 5 gapfill ở các slide tiếp theo, KHÔNG reveal đáp án. Sau đó mới đọc.');
C.mcqs.forEach((q,i)=>add(5,'mcqPreview',`Read the questions first · ${i+1}/5`,{q,notes:'Chỉ preview nhiệm vụ; không chữa. Học sinh dùng handout giữ câu hỏi khi đọc.'}));
C.gapfill.forEach((q,i)=>add(5,'gapPreview',`Predict the word form · ${i+1}/5`,{q,notes:`Elicit loại từ, không lộ từ đáp án. Gợi ý GV: ${q.wordForm}. HS đọc và điền trên handout.`}));
C.reading.suggestedSlides.forEach((ids,i)=>add(5,'reading',`The Missing Crown · ${i+1}/5`,{paragraphs:ids.map(n=>C.reading.paragraphs[n-1]),notes:'HS đọc, làm MCQ/gapfill trên handout. Giữ đủ thời gian; Next chỉ khi lớp sẵn sàng. Không tự động chuyển đoạn.'}));
add(5,'finishReading','Finish your answers',{img:'The Missing Crown - Illustration 2.png',notes:'Cho HS hoàn thành handout và so sánh theo cặp. Sau đó chữa theo trình tự bài đọc. Evidence ở từng câu được trích nguyên văn, đáp án suy ra từ bài đọc.'});
// Correct in story order, preserving original exercise numbering.
[[0,0],[1,1],[2,2],[3,3],[4,4]].forEach(([m,g])=>{add(5,'mcq',`Exercise 1 · Question ${m+1}`,{q:C.mcqs[m],notes:'Cho HS giải thích evidence trước khi Next hiện lời giải. Đáp án '+C.mcqs[m].correct+'.'});add(5,'gap',`Exercise 2 · Sentence ${g+1}`,{q:C.gapfill[g],notes:'ONE WORD from the story. Đáp án: '+C.gapfill[g].answer+'. Cho HS nêu evidence rồi Next chữa.'});});
C.patterns.forEach((q,i)=>add(5,'pattern','Notice the pattern',{q,notes:'Chỉ nhận diện nhanh, không biến thành grammar lesson. Chỉ vào ví dụ và pattern, nối sang buổi sau sẽ nói về hobbies của chính HS.'}));
add(6,'recall','Can you remember our three groups?',{notes:'5 phút consolidation. Elicit ba nhóm trước, Next hiện mental model. Nhắc học cả cụm, không học random.'});
add(6,'exit','Exit ticket',{notes:'Mỗi HS nói một FULL hobby phrase, không trùng bạn ngay trước. Không nhận noun riêng. Dùng handout/word list hỗ trợ nếu cần.'});
add(6,'end','Great job!',{img:'A02',notes:'Kết thúc. Buổi sau: học cách nói về hobbies của bản thân. Có thể quay lại từng stage bằng Lessons.'});
let index=0,phase=0,states={},timer=null,teacherWindow=null,channel,teacherLiveNotes='';const teacher=new URLSearchParams(location.search).has('teacher')||location.hash==='#teacher';
try{channel=new BroadcastChannel('pf-u8l1');}catch{}
let secs=0,running=false;
const $=s=>document.querySelector(s);
function state(){return states[index]||(states[index]={phase:0,selected:null,seconds:null});}
function maxPhase(s){return ['mcq','gap','recall','break'].includes(s.type)?1:0;}
function roundOf(s){return Math.max(0,Math.min((s.rounds?.length||1)-1,state().round||0));}
function dynamicNotes(s){if(s.type==='charadeGame'){const n=s.rounds[roundOf(s)];return `THẺ BÍ MẬT ${roundOf(s)+1}/${s.rounds.length}: ${H[n-1]}. Chỉ người diễn xem. Bấm Start timer sau khi người diễn sẵn sàng; Reveal chỉ sau khi lớp đã đoán.`;}return s.notes||teacherBase;}
function sync(){const payload={kind:'state',index,phase,notes:dynamicNotes(D[index]),title:D[index].title,total:D.length,miniRound:state().round||0};channel?.postMessage(payload);if(teacherWindow&&!teacherWindow.closed)teacherWindow.postMessage(payload,'*');}
function stopTimer(){clearInterval(timer);timer=null;running=false;}
function timerStart(duration){stopTimer();secs=state().seconds??duration;if(secs<=0)secs=duration;running=true;timer=setInterval(()=>{secs=Math.max(0,secs-1);state().seconds=secs;updateClock();if(secs===0){stopTimer();const fb=$('#timeMessage');if(fb)fb.textContent=D[index].type==='charade'?'Time’s up! Other team: your turn.':'Welcome back!';}},1000);updateClock();}
function updateClock(){const t=$('#clock');if(t)t.textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}`;const b=$('#pauseTimer');if(b)b.textContent=running?'Pause':'Resume';}
function revealNextVocab(s){const shown=state().revealedCount||0;if(shown>=s.ids.length)return false;state().revealedCount=shown+1;render();return true;}
function next(){const s=D[index];if(s.type==='vocab'&&revealNextVocab(s))return;if(s.type==='charade'&&phase===0){state().seconds=10;phase=1;state().phase=1;render();timerStart(10);return;}if(s.type==='charade'&&phase===1){stopTimer();phase=2;state().phase=2;render();return;}if(s.type==='break'&&phase===0){state().seconds=300;phase=1;state().phase=1;render();timerStart(300);return;}if(phase<maxPhase(s)){phase++;state().phase=phase;render();return;}if(index<D.length-1){stopTimer();index++;phase=state().phase;render();}}
function prev(){stopTimer();if(phase>0){phase--;state().phase=phase;}else if(index>0){index--;phase=state().phase;}render();}
function jump(i){stopTimer();index=Math.max(0,Math.min(D.length-1,i));phase=state().phase;render();}
function timerHtml(){return `<div class="timer" id="clock">${D[index].type==='break'?'5:00':'0:10'}</div><div class="timer-controls"><button class="action secondary" id="pauseTimer">Pause</button><button class="action secondary" id="resetTimer">Restart timer</button></div><p id="timeMessage" class="caption"></p>`;}
function grid(ids,dense=false){const cols=dense?5:ids.length<=3?ids.length:ids.length===4?4:3,shown=Math.min(ids.length,state().revealedCount||0);return `<div class="vocab-grid progressive" data-vocab-reveal tabindex="0" role="group" aria-label="Vocabulary. Press Enter or Space to reveal the next phrase." style="grid-template-columns:repeat(${cols},1fr);grid-auto-rows:${dense?'160px':'auto'}">${ids.map((n,i)=>`<div class="vocab-card ${dense?'small':''} ${i<shown?'is-visible':''}" aria-hidden="${i<shown?'false':'true'}" style="${dense?'':`height:${ids.length>4?330:580}px`}">${image(hid(n),'',H[n-1])}<strong>${esc(H[n-1])}</strong></div>`).join('')}</div>`;}
function readingChunks(text){const verbs=/\b(finally have|decide|brings|spends|prefers|makes|enjoys|cannot sit|stays|sings|plays|touches|look|checks|runs|searches|can find|stops|took|sit|is flying|is|cries|follow|see|gets|laughs|says|can solve)\b/i;return text.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(raw=>{const safe=esc(raw.trim()),m=safe.match(verbs);if(!m)return `<span class="reading-sentence"><span class="support">${safe}</span></span>`;const at=m.index,verb=m[0];return `<span class="reading-sentence"><span class="sv"><b class="subject">${safe.slice(0,at).trim()}</b> <b class="verb">${verb}</b></span><span class="support">${safe.slice(at+verb.length)}</span></span>`;}).join(' ')||esc(text);}
function options(opts,correct=null){return `<div class="options">${opts.map((o,i)=>UI.optionHTML({letter:String.fromCharCode(65+i),text:o,state:phase&&i===correct?'correct':!phase&&state().selected===i&&i!==correct?'wrong':'idle',attributes:{'data-choice':i}})).join('')}</div>`;}
function view(s){switch(s.type){
case'cover':return `<div class="split"><div>${UI.pillHTML({text:'UNIT 8 · LESSON 1'})}<h1 class="title" style="margin:40px 0">Names of<br>hobbies</h1><p>Learn the whole phrase.<br>Organise it. Remember it.</p></div>${image('MM01')}</div>`;
case'instructions':return `<div class="split"><div class="instructions">${UI.pillHTML({text:'How to play'})}<ol>${s.items.map((x,i)=>UI.instructionCardHTML({number:i+1,text:x})).join('')}</ol></div><div><h2 class="title" style="text-align:center;margin-bottom:25px">${esc(s.title)}</h2>${image(s.img)}</div></div>`;
case'wyr':return `<div class="center">${image(s.img,'map-image','Two hobby choices')}</div>`;
case'vocab':return grid(s.ids,s.dense);
case'map':return image(s.img,'map-image','Hobbies organised into Sports, Art, Technology and Media');
case'organise':return `<div class="center"><h1>Learn the <span class="red">whole phrase!</span></h1><div class="categories" style="width:100%;margin:35px 0"><div class="category">SPORTS<br><small>PLAY · GO · DO</small></div><div class="category">ART</div><div class="category">TECHNOLOGY<br>& MEDIA</div></div><h2>Don’t learn vocabulary randomly.<br><span class="red">Organise it.</span></h2></div>`;
case'sortGame':{const r=roundOf(s),q=s.rounds[r],solved=state().solved;return `<div class="mini-app center"><div class="mini-top"><span>Round ${r+1} / ${s.rounds.length}</span><button class="mini-reset" data-mini="reset">Reset</button></div>${image(hid(q.h),'sort-img',H[q.h-1])}<h2>${esc(H[q.h-1])}</h2><div class="categories mini-options">${['SPORTS','ART','TECHNOLOGY & MEDIA'].map((x,i)=>`<button class="category" data-mini-choice="${i}" data-state="${solved&&i===q.correct?'correct':'idle'}">${x}</button>`).join('')}</div><p class="feedback" id="feedback">${solved?'Correct! Say the whole phrase.':'Choose a group.'}</p>${solved?`<button class="action" data-mini="next">${r===s.rounds.length-1?'Finish':'Next item →'}</button>`:''}</div>`;}
case'verbGame':{const r=roundOf(s),q=s.rounds[r],solved=state().solved;return `<div class="mini-app center"><div class="mini-top"><span>Round ${r+1} / ${s.rounds.length}</span><button class="mini-reset" data-mini="reset">Reset</button></div><p>Raise the correct verb card.</p><h1><span class="red">${solved?esc(q.answer.toLowerCase()):'____'}</span> ${esc(q.prompt)}</h1><div class="categories mini-options four">${['PLAY','GO','DO','MAKE'].map((x,i)=>`<button class="category" data-mini-choice="${i}" data-state="${solved&&x===q.answer?'correct':'idle'}">${x}</button>`).join('')}</div><p class="feedback" id="feedback">${solved?'Say the whole phrase: '+esc(q.fullPhrase):'Choose one card.'}</p>${solved?`<button class="action" data-mini="next">${r===s.rounds.length-1?'Finish':'Next item →'}</button>`:''}</div>`;}
case'charadeGame':{const r=roundOf(s),n=s.rounds[r],revealed=state().revealed;return `<div class="mini-app charade-layout"><div class="center charade-stage"><div class="mini-top"><span>Round ${r+1} / ${s.rounds.length}</span><button class="mini-reset" data-mini="reset">Reset</button></div><h2>${revealed?'Say the whole phrase!':'Act it out!'}</h2>${revealed?`<div class="charade-reveal reveal">${image(hid(n),'charade-img',H[n-1])}<p class="answer">${esc(H[n-1])}</p></div>`:`<div class="charade-wait"><p>No speaking.<br>Your team guesses.</p>${timerHtml()}</div>`}<div class="mini-actions">${revealed?`<button class="action" data-mini="next">${r===s.rounds.length-1?'Finish':'Next card →'}</button>`:`<button class="action" data-mini="reveal">Reveal after guesses</button>`}</div></div></div>`;}
case'break':return `<div class="center"><h1 class="title">BREAK TIME</h1>${phase?timerHtml():'<p class="timer">5 minutes</p><p>Stretch. Relax. Come back ready!</p><p class="caption">Next starts the timer.</p>'}</div>`;
case'princessMatch':{const names=['Rapunzel','Moana','Ariel'],order=[1,2,0],matches=state().matches||{},starts=[[1030,650],[170,650],[600,650]],targets=[[125,255],[610,92],[1050,245]];return `<div class="match-app"><div class="match-stage">${image('The Missing Crown - Illustration 1.png','hero-img','Three princesses having a picnic by a lake')}<svg class="match-lines" viewBox="0 0 1200 675" aria-hidden="true">${Object.entries(matches).map(([label,target])=>`<line x1="${starts[label][0]}" y1="${starts[label][1]}" x2="${targets[target][0]}" y2="${targets[target][1]}"/>`).join('')}</svg><div class="drop-zones">${names.map((n,i)=>`<button data-match-target="${i}" aria-label="Position ${i+1}"><span>${i+1}</span></button>`).join('')}</div></div><div class="match-labels">${order.map(i=>`<button draggable="true" data-match-label="${i}" data-state="${matches[i]!==undefined?'correct':'idle'}">${names[i]}</button>`).join('')}</div><div class="match-footer"><p id="feedback" class="feedback">Drag a name to the correct princess.</p><button class="mini-reset" data-mini="reset">Reset</button></div></div>`;}
case'predict':return `<div class="split">${image('The Missing Crown - Illustration 1.png')}<div class="center"><h2>What do you think<br>their hobbies are?</h2><p>Look at the picture.<br>Tell your partner.</p></div></div>`;
case'mcqPreview':case'mcq':return `<div class="mcq-layout" style="max-width:1510px;margin:auto"><p class="question">${esc(s.q.question)}</p>${options(s.q.options,s.type==='mcq'?s.q.correctIndex:null)}${s.type==='mcq'&&phase?UI.evidenceHTML({text:s.q.evidence,className:'reveal'}):`<p class="caption" style="margin-top:25px">${s.type==='mcqPreview'?'Read the question. Then find the answer in the story.':'Choose an answer. Explain your evidence.'}</p>`}</div>`;
case'gapPreview':case'gap':return `<div class="center"><p style="font-size:48px;line-height:1.5;max-width:1460px">${esc(s.q.sentence).replace('_____',`<span class="gap">${s.type==='gap'&&phase?esc(s.q.answer):'  '}</span>`)}</p>${s.type==='gap'&&phase?UI.evidenceHTML({text:s.q.evidence,className:'reveal'}):`<p>${s.type==='gapPreview'?'What kind of word is missing?':'Write ONE WORD from the story.'}</p>`}</div>`;
case'reading':return `<div class="center" style="text-align:left;align-items:stretch"><div class="reading"><h2 class="reading-title">The Missing Crown</h2>${s.paragraphs.map(p=>`<p>${readingChunks(p)}</p>`).join('')}<div class="reading-key"><span>Who / what</span><span>action</span><span>supporting detail</span></div></div></div>`;
case'finishReading':return `<div class="split">${image(s.img)}<div class="center"><h2>Finish your answers.</h2><p>Compare with a partner.<br>Find evidence in the story.</p></div></div>`;
case'pattern':return `<div class="center"><div class="pattern">${esc(s.q.pattern)}</div><p class="pattern-example">“${esc(s.q.example)}”</p><p class="caption">Notice the pattern. Say the example.</p></div>`;
case'recall':return phase?image('MM01','map-image','Hobbies mental model'):`<div class="center"><h2>How do we organise hobbies?</h2><div class="categories" style="width:100%;margin:50px 0"><div class="category">?</div><div class="category">?</div><div class="category">?</div></div><p>Say the three groups.<br>Give a full hobby phrase for each.</p></div>`;
case'exit':return `<div class="center"><div style="border:7px double var(--red);background:#fae9ca;padding:65px 100px;border-radius:55px"><h1 class="title">EXIT TICKET</h1><h2 style="margin:35px 0">Say ONE full hobby phrase.</h2><p>Choose a different phrase<br>from the person before you.</p><p class="red" style="margin-top:30px">★ ★ ★</p></div></div>`;
case'end':return `<div class="split"><div class="center"><h1 class="title">Great job!</h1><h2>See you next lesson.</h2><p>Next time: talk about<br>your own hobbies.</p></div>${image(s.img)}</div>`;
default:return '';}}
function fit(){if(teacher)return;const scale=Math.min(innerWidth/1920,(innerHeight-58)/1080);$('#viewport').style.width=1920*scale+'px';$('#viewport').style.height=1080*scale+'px';$('#slide').style.transform=`scale(${scale})`;}
function render(){if(teacher)return;const s=D[index],label=s.stage===5?'Reading':s.stage===2?'Vocabulary':s.stage===6?'Summary':'Activity',icon=label==='Reading'?'reading':label==='Summary'?'summary':'activity';$('#slide').innerHTML=`<div class="clean-shell" aria-hidden="true"><div class="shell-panel"></div></div><p class="stage">${esc(stages[s.stage])}</p><img class="logo" src="assets/brand/logo.svg" alt="DOL IELTS Đình Lực"><div class="content enter">${UI.activityBarHTML({label,title:s.title,icon})}<div class="body">${view(s)}</div></div>`;
$('#progress').textContent=`${index+1} / ${D.length}${phase?' · reveal':''}`;$('#prev').disabled=index===0&&phase===0;$('#next').disabled=index===D.length-1;$('#next').textContent=s.type==='vocab'&&(state().revealedCount||0)<s.ids.length?'Reveal →':(s.type==='charade'&&phase===0||s.type==='break'&&phase===0)?'Start →':(s.type==='charade'&&phase===1||phase<maxPhase(s))?'Reveal →':'Next →';
$$('[data-choice]').forEach(b=>{if(s.type==='mcqPreview'||phase>0){b.disabled=true;return;}b.onclick=()=>{const choice=Number(b.dataset.choice);state().selected=choice;const correct=s.type==='sort'?s.correct:s.type==='verb'?['PLAY','GO','DO','MAKE'].indexOf(s.q.answer):s.q.correctIndex;if(choice===correct){phase=1;state().phase=1;render();}else{b.dataset.state='wrong';b.style.background='#ffe1da';const fb=$('#feedback');if(fb){fb.textContent='Try again.';fb.classList.add('wrong');}}};});
$('[data-mini-choice]')&&$$('[data-mini-choice]').forEach(b=>b.onclick=()=>{const r=roundOf(s),choice=Number(b.dataset.miniChoice),correct=s.type==='sortGame'?s.rounds[r].correct:['PLAY','GO','DO','MAKE'].indexOf(s.rounds[r].answer);if(choice===correct){state().solved=true;render();}else{b.dataset.state='wrong';b.classList.remove('shake');void b.offsetWidth;b.classList.add('shake');const fb=$('#feedback');if(fb){fb.textContent='Try again.';fb.className='feedback wrong';}}});
$$('[data-mini]').forEach(b=>b.onclick=()=>{const action=b.dataset.mini;if(action==='reset'){stopTimer();states[index]={phase:0,round:0};render();return;}if(action==='reveal'){state().revealed=true;stopTimer();render();return;}if(action==='next'){const last=roundOf(s)>=(s.rounds?.length||1)-1;if(last){state().completed=true;const fb=$('#feedback');if(fb)fb.textContent='Activity complete!';}else{state().round=roundOf(s)+1;state().solved=false;state().revealed=false;state().seconds=null;phase=0;render();}}});
const vocabReveal=$('[data-vocab-reveal]');if(vocabReveal){vocabReveal.onclick=()=>revealNextVocab(s);vocabReveal.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();revealNextVocab(s);}};}
if(s.type==='princessMatch'){let activeLabel=null;const connect=(label,target,button)=>{if(label===target){state().matches={...(state().matches||{}),[label]:target};activeLabel=null;render();}else{button?.classList.add('shake');const fb=$('#feedback');if(fb){fb.textContent='Try again.';fb.className='feedback wrong';}}};$$('[data-match-label]').forEach(b=>{b.ondragstart=e=>{activeLabel=Number(b.dataset.matchLabel);e.dataTransfer?.setData('text/plain',b.dataset.matchLabel);};b.onclick=()=>{activeLabel=Number(b.dataset.matchLabel);$$('[data-match-label]').forEach(x=>x.classList.toggle('active',x===b));};});$$('[data-match-target]').forEach(b=>{b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();connect(Number(e.dataTransfer?.getData('text/plain')),Number(b.dataset.matchTarget),b);};b.onclick=()=>{if(activeLabel!==null)connect(activeLabel,Number(b.dataset.matchTarget),b);};});}
if($('#clock')){secs=state().seconds??(s.type==='break'?300:10);updateClock();$('#pauseTimer').onclick=()=>{if(running){stopTimer();updateClock();}else timerStart(s.type==='break'?300:10);};$('#resetTimer').onclick=()=>{state().seconds=s.type==='break'?300:10;timerStart(state().seconds);};}
fit();sync();}
function $$(s){return [...document.querySelectorAll(s)];}
function receive(e){const p=e.data;if(!p)return;if(teacher&&p.kind==='state'){index=p.index;phase=p.phase;teacherLiveNotes=p.notes||'';teacherRender();}else if(!teacher&&p.kind==='command'){if(p.command==='next')next();if(p.command==='prev')prev();if(p.command==='jump')jump(p.index);}else if(!teacher&&p.kind==='hello')sync();}
if(channel)channel.onmessage=receive;window.addEventListener('message',e=>{if(e.source===teacherWindow||e.source===window.opener)receive(e);});
function send(command,i){const p={kind:'command',command,index:i};if(window.opener&&!window.opener.closed)window.opener.postMessage(p,'*');else channel?.postMessage(p);}
function teacherRender(){$('#teacherTitle').textContent=`${index+1}/${D.length} · ${D[index].title}`;$('#teacherNote').textContent=teacherLiveNotes||dynamicNotes(D[index]);$('#teacherList').value=index;$('#teacherPhase').textContent=`Student screen: ${phase?'reveal / activity running':'question / task'}`;}
function bootTeacher(){document.body.className='teacher-page';document.body.innerHTML=`<h1>Teacher view · U8L1</h1><p class="warning">PRIVATE — keep this window on your laptop, not on the classroom TV. Use Extend displays, not Mirror.</p><p class="tag">Prompts for Right Card and Tiny Word Detective were added for this lesson. Reading answers are checked against the story.</p><select id="teacherList" aria-label="Jump to slide">${D.map((s,i)=>`<option value="${i}">${i+1}. ${esc(s.title)}</option>`).join('')}</select><h2 id="teacherTitle" style="font-size:28px;margin-top:22px"></h2><p id="teacherPhase" class="status"></p><div id="teacherNote" class="note"></div><button id="tp">← Back</button><button id="tn">Next →</button><p style="margin-top:25px"><a href="teacher-guide.html" target="_blank">Printable teacher script & materials</a></p>`;$('#tp').onclick=()=>send('prev');$('#tn').onclick=()=>send('next');$('#teacherList').onchange=e=>send('jump',Number(e.target.value));teacherRender();if(window.opener)window.opener.postMessage({kind:'hello'},'*');else channel?.postMessage({kind:'hello'});}
if(teacher){bootTeacher();return;}
$('#prev').onclick=prev;$('#next').onclick=next;$('#fullBtn').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});};$('#teacherBtn').onclick=()=>{const url=new URL(location.href);url.hash='teacher';teacherWindow=window.open(url.href,'pf-u8l1-teacher','width=850,height=800');if(!teacherWindow)alert('Please allow this lesson to open the teacher window, or open teacher-guide.html separately.');};
$('#menuBtn').onclick=()=>$('#menu').showModal();$('#closeMenu').onclick=()=>$('#menu').close();$('#chapters').innerHTML=stages.map((s,n)=>`<button data-stage="${n}">${esc(s)}</button>`).join('');$$('[data-stage]').forEach(b=>b.onclick=()=>{jump(D.findIndex(s=>s.stage===Number(b.dataset.stage)));$('#menu').close();});
addEventListener('keydown',e=>{if($('#menu').open||/INPUT|SELECT|TEXTAREA/.test(document.activeElement?.tagName))return;if(e.key===' '&&document.activeElement?.tagName==='BUTTON')return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();next();}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();prev();}});addEventListener('resize',fit);render();
// Read-only diagnostics used during QA and by future maintainers.
window.LESSON_INFO={slides:D.map(({q,notes,...s},i)=>({index:i,type:s.type,title:s.title,stage:s.stage})),count:D.length,componentRuntime:UI.version,componentIds:UI.ids};
})();
